export * from './admValidation'
export * from './alunoValidation'
export * from './candidatoValidation'
export * from './chapaValidation'
export * from './funcionarioValidation'
export * from './usuarioValidation'
export * from './votacaoValidation'
export * from './zonaValidation'